# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import text_analyzer_pb2 as text__analyzer__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in text_analyzer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TextAnalyzerStub(object):
    """Define the service for analyzing text content.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeText = channel.unary_unary(
                '/TextAnalyzer/AnalyzeText',
                request_serializer=text__analyzer__pb2.AnalysisRequest.SerializeToString,
                response_deserializer=text__analyzer__pb2.AnalysisResponse.FromString,
                _registered_method=True)


class TextAnalyzerServicer(object):
    """Define the service for analyzing text content.
    """

    def AnalyzeText(self, request, context):
        """RPC method to analyze text and return various statistics.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextAnalyzerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeText': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeText,
                    request_deserializer=text__analyzer__pb2.AnalysisRequest.FromString,
                    response_serializer=text__analyzer__pb2.AnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TextAnalyzer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('TextAnalyzer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TextAnalyzer(object):
    """Define the service for analyzing text content.
    """

    @staticmethod
    def AnalyzeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TextAnalyzer/AnalyzeText',
            text__analyzer__pb2.AnalysisRequest.SerializeToString,
            text__analyzer__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
