# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: text_analyzer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'text_analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13text_analyzer.proto\"\'\n\x0f\x41nalysisRequest\x12\x14\n\x0ctext_content\x18\x01 \x01(\t\"\x8b\x01\n\x10\x41nalysisResponse\x12\x12\n\nword_count\x18\x01 \x01(\x05\x12\x16\n\x0esentence_count\x18\x02 \x01(\x05\x12\x14\n\x0clongest_word\x18\x03 \x01(\t\x12\x15\n\rshortest_word\x18\x04 \x01(\t\x12\x1e\n\x16server_processing_time\x18\x05 \x01(\x01\x32\x42\n\x0cTextAnalyzer\x12\x32\n\x0b\x41nalyzeText\x12\x10.AnalysisRequest\x1a\x11.AnalysisResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYSISREQUEST']._serialized_start=23
  _globals['_ANALYSISREQUEST']._serialized_end=62
  _globals['_ANALYSISRESPONSE']._serialized_start=65
  _globals['_ANALYSISRESPONSE']._serialized_end=204
  _globals['_TEXTANALYZER']._serialized_start=206
  _globals['_TEXTANALYZER']._serialized_end=272
# @@protoc_insertion_point(module_scope)
